version: "2.2"
services:
# Flink
  jobmanager:
    image: flink:java11
    restart: always
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager     
        jobmanager.memory.process.size: 5000m
        jobmanager.memory.heap.size: 4000m
    volumes:
      - 'C:\shared:/shared'

  taskmanager:
    image: flink:java11
    restart: always
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2  
        taskmanager.memory.heap.size: 4000m
        taskmanager.memory.process.size: 5000m
    volumes:
      - 'C:\shared:/shared'